version: "2.2"

services:
  validator:
    image: hyperledger/sawtooth-validator:1.1
    volumes:
      - keys:/shared_keys
      - ./entrypoints:/entrypoints
    expose:
      - 4004
      - 8800
    entrypoint: /entrypoints/validator-1.sh
    stop_signal: SIGKILL

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.1
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-1:4004 --bind rest-api-1:8008
    stop_signal: SIGKILL

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.1
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL
