version: "2.2"

services:
  rest-api:
    image: hyperledger/sawtooth-rest-api:1.1
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-1:4004 --bind rest-api-1:8008
    stop_signal: SIGKILL

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.1
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL
