#!/usr/bin/env bash

function docker_compose_wrapper() {
    if [ $NO_COLOR -eq 1 ]; then
        # https://superuser.com/a/380778
        # https://stackoverflow.com/a/31151808
        { docker-compose "$@" 2>&1 1>&3 3>&- | sed 's/\x1b\[[0-9;]*m//g'; } 3>&1 1>&2 | sed 's/\x1b\[[0-9;]*m//g'
    else
        docker-compose "$@"
    fi
}
#
function onexit() {
    local stat=${1:-$?}
    log "Cleaning up."
    docker_compose_wrapper -f "docker-compose.yaml" down -v
    log "Exiting ${prog} with $stat."
    exit $stat
}


docker_compose_wrapper -f "docker-compose.yaml" down -v
docker_compose_wrapper -f "docker-compose.yaml" build
docker_compose_wrapper -f "docker-compose.yaml" up --abort-on-container-exit

onexit
